[env:portable_ui_s3_i80]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc1-n16r8

monitor_speed = 115200

board_build.partitions = huge_app.csv

build_flags =
  -Iinclude
  -DCORE_DEBUG_LEVEL=3
  -mfix-esp32-psram-cache-issue
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1


lib_deps =
  olikraus/U8g2@^2.35.30
  lahavg/QMI8658@^1.0.1
  solderedelectronics/Soldered PCF85063A RTC Library @ ^1.0.0

